export const UI_LABELS = {
    CANCEL: 'Cancel',
    SAVE: 'Save',
    COMMENT: 'Comment',
    EDIT: 'Edit',
    DELETE: 'Delete',
    CONFIRM: 'Confirm',
    CLOSE: 'Close',
    TASK_NOT_FOUND: 'Task not found',
    BACK_TO_BOARD: 'Back to board',
    NO_DESCRIPTION: 'No description provided.',
    DESCRIPTION: 'Description',
    ACTIVITY: 'Activity',
    CHECKLISTS: 'Checklists',
    ADD_ITEM: 'Add an item',
    ADD_CHECKLIST: 'Add Checklist',
    LABELS: 'Labels',
    PRIORITY: 'Priority',
    ASSIGNEE: 'Assignee',
    UNASSIGNED: 'Unassigned',
    CLEAR_ASSIGNEE: 'Clear assignee',
    ADD_TAG: 'Add a tag...',
    SAVE_TASK: 'Save Task',
    CREATE_TASK: 'Create New Task',
    EDIT_TASK: 'Edit Task',
    TASK_TITLE: 'Task Title',
    ADD_DETAILS: 'Add more details... (Markdown supported)',
    NOTHING_TO_PREVIEW: 'Nothing to preview',
    UNSAVED_CHANGES: 'You have unsaved changes. Discard them?',
};
